### ISSUE TITLE
install mas by default - fresh install from applestore failed because mas is missing

### ISSUE THREAD

**Issue by jangalinski** [ayltai/BrewMyMac#11]
My first run:

Press Command+C to quit now if you have not already signed in to App Store. Otherwise, press any key to continue ....⏳ Installing App Store apps ...
/bin/bash: line 45: mas: command not found
❌ Failed to install Amphetamine from App Store

after adding "mas" manually it worked. Since mas is required, it could be automatically installed when I pick an app from the appstore.

**Comment by ayltai** [comment]
Fixed in [release v1.1.4](https://github.com/ayltai/BrewMyMac/releases/tag/release%2Fv1.1.4)
